# Generated by Django 2.1.1 on 2019-03-29 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('os', models.CharField(max_length=200)),
                ('screen_resolution', models.CharField(max_length=200)),
                ('camera_resolution', models.CharField(max_length=200)),
                ('ram', models.IntegerField()),
                ('cpu', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ApplePhone',
            fields=[
                ('phone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phones.Phone')),
                ('air_pods', models.BooleanField()),
                ('face_id', models.BooleanField()),
                ('apple_pay', models.BooleanField()),
            ],
            bases=('phones.phone',),
        ),
        migrations.CreateModel(
            name='PechenkaPhone',
            fields=[
                ('phone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phones.Phone')),
                ('fm_radio', models.BooleanField()),
            ],
            bases=('phones.phone',),
        ),
        migrations.CreateModel(
            name='SamsungPone',
            fields=[
                ('phone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phones.Phone')),
                ('samsung_pay', models.BooleanField()),
            ],
            bases=('phones.phone',),
        ),
    ]
